### PR TITLE
Increased Performance

### PR DESCRIPTION
**Pull request by blazeykat**
please dont look at the code

### CODE REVIEW

**Comment by An3s079** [comment]
Nice try! I see a few issues with this pull request however, please try to refrain from closing the application without any user input.

**Comment by blazeykat** [comment]
please an3s

**Review by An3s079 — CHANGES_REQUESTED** [review]
dont close application on startup

**Review by An3s079 — CHANGES_REQUESTED** [review]
this is literally putting malware on someones C: drive blazey

**Comment by blazeykat** [comment]
naw

**Comment by blazeykat** [comment]
an3s its a 1 in a thousand chance comeonnnn

**Comment by An3s079** [comment]
dont shill and make it something funny how about that

**Comment by blazeykat** [comment]
cant im not funny

**Comment by blazeykat** [comment]
nevermind im really funny

**Comment by An3s079** [comment]
👍

**Pull request merged**
